Updated brilcal version and 2015 norm tag. Added 2017 run boundary (normtag file to be added).

diff --git a/ntuple_production/getlumi b/ntuple_production/getlumi
--- a/ntuple_production/getlumi
+++ b/ntuple_production/getlumi
@@ -9,6 +9,25 @@ Calculates processed integrated luminosity from a crab job lumi section report.
 EOF
 fi
 
+BRILCAL_INSTALL_DIR="$HOME/.local"
+
+export PATH="$BRILCAL_INSTALL_DIR"/bin:/afs/cern.ch/cms/lumi/brilconda-1.1.7/bin:$PATH
+
+
+if [ "$1" = --install ]; then
+    if [ -e "$BRILCAL_INSTALL_DIR" ]; then
+	echo "Delete directory $BRILCAL_INSTALL_DIR (y/n) ?" 1>&2
+	read n
+	if [ $n = "y" -o $n = "Y" ]; then
+	    rm -r "$BRILCAL_INSTALL_DIR"
+	else
+	    echo "Aborting installation." 1>&2
+	fi
+    fi
+    pip install --install-option="--prefix=$BRILCAL_INSTALL_DIR" brilws
+    exit $?
+fi
+
 if [ "$1" = -r ]; then
     recorded_only=y
     shift
@@ -40,12 +59,14 @@ except (IOError, ValueError):
     system.stderr.write("\nFailed to read run list from json file %s.\n\n" % jsonFile)
 run_min=min(r)
 run_max=max(r)
-if run_min > 256600 and  run_max < 258200:
+if run_min > 256600 and  run_max < 263798:
     print 2015
-elif run_min > 258200:
+elif run_min >= 263798 and run_max < 286655:
     print 2016
+elif run_min >= 286655:
+    print 2017
 else:
-    print "?"
+    print "? (run min: %d, run max: %d)" % (run_min, run_max)
 EOF
 }
 
@@ -54,6 +75,8 @@ dataset="`run "$json"`"
 if [ "$dataset" = 2015 ]; then
 #Normtag of 2015 data Updated on Mar. 31, 16
     normtag=/afs/cern.ch/user/l/lumipro/public/normtag_file/moriond16_normtag.json
+#Update on Apr. 11, 2016. See https://hypernews.cern.ch/HyperNews/CMS/get/physics-announcements/4482.html
+    normtag=/afs/cern.ch/user/l/lumipro/public/Normtags/normtag_PHYSICS.json
 elif [ "$dataset" = 2016 ]; then
     normtag=/afs/cern.ch/user/l/lumipro/public/Normtags/normtag_DATACERT.json
 else
@@ -63,14 +86,11 @@ fi
 
 #python /afs/cern.ch/user/m/marlow/public/lcr2/lcr2.py -i  "$json" | filter
 
-export PATH=$HOME/.local/bin:/afs/cern.ch/cms/lumi/brilconda-1.0.3/bin:$PATH
-
-#check if brilcalc 2.2.0 is already installed...
-[ -x $HOME/.local/bin/brilcalc ] && ~/.local/bin/brilcalc --version | grep -q '^2\.2\.0$' 
-#... if not, install it:
-if [ $? != 0 ]; then
-    pip uninstall brilws
-    pip install --install-option="--prefix=$HOME/.local" brilws
+#check if brilcalc is already installed with expected version
+install=n
+if ! [ -x "$BRILCAL_INSTALL_DIR/bin/brilcalc" ]; then
+    echo "$BRILCAL_INSTALL_DIR/bin/brilcalc was not found. You need to install brilcal using the command getlumi --install." 1>&2
+    exit 1
 fi
 
 #brilcalc lumi -i "$json" -n 0.962 | filter
@@ -79,7 +99,7 @@ fi
 #Updated on Dec. 6, 15 to normtag announced in https://hypernews.cern.ch/HyperNews/CMS/get/luminosity/544.html
 #brilcalc lumi --normtag /afs/cern.ch/user/l/lumipro/public/normtag_file/OfflineNormtagV2.json -i "$json"  | filter
 echo "Using normtag $normtag." 1>&2
-brilcalc lumi --normtag  "$normtag" -i "$1"  --without-checkjson | filter
+$BRILCAL_INSTALL_DIR/bin/brilcalc lumi --normtag  "$normtag" -i "$1"  --without-checkjson | filter
 
 
 #pip uninstall brilws
